### PR TITLE
AWS Cloud Storage Setup

### PR DESCRIPTION
**Pull request by callea2**
PT Story: https://www.pivotaltracker.com/story/show/129446531
              https://www.pivotaltracker.com/story/show/129602095

Changes proposed in this pull request:
- Adds and setup Amazon S3 Bucket
- Adds dotenv gem
  (You will receive .env file information through chat)

What I have learned working on this feature:
- How to configure and setup carrierwave-aws
- How to use dotenv

Screenshots:
skarmavbild 2016-09-01 kl 16 36 33
(This picture was uploaded from localhost)

Ready for review!

### CODE REVIEW

**Comment by tochman** [comment]
I can't see that you have modified the `.gitignore` with `.env` to exclude that file from version control.

**Comment by luciademoja** [comment]
@tochman cause it was already in there 
skarmavbild 2016-09-01 kl 16 44 58

**Comment by tochman** [comment]
Mind the commit messages please.

**Comment by tochman** [comment]
Can't really see whats in the screenshot :-(

**Comment by luciademoja** [comment]
@lollypop27 @MikaelFeher whenever you have time to review this it's ready!

**Pull request merged**
