### PR TITLE
Styled all headings to be the same, update design

### PR DESCRIPTION
**Pull request by lollypop27**
PT Story: https://www.pivotaltracker.com/story/show/129577535

Changes proposed in this pull request:
- Fixed button styles
- Added submenu to dashboard
- Fixed main herders to look consistent
- Styled Dashboard
- Moved login name to right of menu and made visible
- Updated design background and layout on display pages

What I have learned working on this feature:
That styling is a continuous task

@luciademoja @MikaelFeher Ready for review!

### CODE REVIEW

**Comment by luciademoja** [comment]
@lollypop27 Did you have a chance to run the step `Then show me an image of the page` to see how the buttons looked like? If so, could you please add a screenshot of that image to this PR so we can see it?

**Comment by callea2** [comment]
Before:
skarmavbild 2016-09-01 kl 11 49 23

After:
skarmavbild 2016-09-01 kl 11 41 42

**Comment by callea2** [comment]
Some other pages need similar treatment. For example:
skarmavbild 2016-09-01 kl 11 56 05

**Comment by lollypop27** [comment]
@callea2 thanks will have a look at that other page

**Comment by lollypop27** [comment]
@luciademoja and @callea2 
I fixed the pages and changed the background, the yellow was killing me, ha ha ha
home_page
dish_display

**Comment by luciademoja** [comment]
@lollypop27 loving the new style 👍  💃

**Pull request merged**
