### PR TITLE
Add to cart button

### PR DESCRIPTION
**Pull request by MikaelFeher**
PT Story: https://www.pivotaltracker.com/story/show/128932993

Changes proposed in this pull request:
- Adds gem acts_as_shopping_cart
- Adds functionality for adding dishes to shopping cart via an "order"-button 
  on the dish display page.

What I have learned working on this feature:
- The basics of adding shopping cart functionality to a rails project.

Ready for review!

### CODE REVIEW

**Comment by tochman** [comment]
@MikaelFeher We changed the User factory so this scenario will automatically fail. Needs to be refactored to use a specific email address when creating the admin user.

**Comment by MikaelFeher** [comment]
I'll fix

**Comment by tochman** [comment]
Any objections to this one?

**Comment by luciademoja** [comment]
None from me @tochman 👍

**Pull request merged**
