### PR TITLE
Css footer header

### PR DESCRIPTION
**Pull request by lollypop27**
PT Story: https://www.pivotaltracker.com/story/show/128640117

Changes proposed in this pull request:
- Refactored fields and updated DB
- Added Foundation.css file and set it has main css file to be called in assets.rb file
- Styling footer and header
- Adding JavaScript too include sticky footer

What I have learned working on this feature:
How to set the main css file to be called in the config > initializers > assets.rb file

@MikaelFeher Ready for review!

### CODE REVIEW

**Comment by tochman** [comment]
Okay so this PR is not okay. We need to follow the workflow with creating feature branches off `develop` There are way to many commits in this one that are already part of the code base. Also, Travis is failing. :-(

**Comment by lollypop27** [comment]
@tochman fixing it now

**Comment by diraulo** [comment]
@lollypop27 The JS issue on Travis was fixed in another PR. So just cherry pick the commits that are actually supposed to be here and submit a new (clean) PR. I can help you with that.

**Comment by diraulo** [comment]
This PR should in principle be closed automatically once #22 is merged

**Comment by diraulo** [comment]
oh well it didn't 😞  -- Closing this one then

**Pull request closed without merging**
