### PR TITLE
Establish visitors geolocation and center map automatically

### PR DESCRIPTION
**Pull request by callea2**
PT Story 1: https://www.pivotaltracker.com/story/show/128494085
PT Story 2: https://www.pivotaltracker.com/story/show/128932385

The map now checks if we're in the test or production environment. If we're in the test environment it sets static coordinates, however, if we're in the production environment it will automatically get the visitor position and center the map. The most logical way to solve one feature happened to include the solution of the other feature as well.

Changes proposed in this pull request:
- Automatically establishes the visitors location
- Centers the map on visitor location
- Adds environment check on landing page
- Minor cucumber refactoring

What I have learned working on this feature:
Working on this refreshed my knowledge of Javascript and once again showed me how valuable pry is when you can utilize it.

Ready for review!

### CODE REVIEW

**Comment by luciademoja** [comment]
@callea2 @rdcsg There seem to be conflicts with the upstream, try to do a pull on your branch to resolve them and then push up again.

**Comment by callea2** [comment]
Fixed now!

**Comment by luciademoja** [comment]
Great! Merging this now 👯

**Comment by tochman** [comment]
For some reason Travis didn't kick in on this one. That needs to be monitored before we decide upon a merge. We are seeing fails on Travis now... ;-)

**Pull request merged**
